### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by FiberAhmed** [Im2rnado/Fort-Shop#4]
Error:

C:\Users\Ahmed\Downloads\Fort-Shop-main\Fort-Shop-main>node test.js
[Fort-Shop] Made by Im2rnado. For support, contact tornado#9999 on Discord
C:\Users\Ahmed\Downloads\Fort-Shop-main\Fort-Shop-main\node_modules\canvas\index.js:48
  return Canvas._registerFont(fs.realpathSync(src), fontFace)
                ^

Error: Could not parse font file
    at registerFont (C:\Users\Ahmed\Downloads\Fort-Shop-main\Fort-Shop-main\node_modules\canvas\index.js:48:17)
    at generateShop (C:\Users\Ahmed\Downloads\Fort-Shop-main\Fort-Shop-main\shop.js:22:3)
    at C:\Users\Ahmed\Downloads\Fort-Shop-main\Fort-Shop-main\test.js:4:46
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

Node.js v17.1.0

**Comment by Gabuiiiyt** [comment]
Hi i resolved this running in the terminel this command: `npm i canvas`.
